### ISSUE TITLE
Request: Expanding Terraform version support

### ISSUE THREAD

**Issue by pedorich-n** [stackbuilders/nixpkgs-terraform#27]
Hello!

I recently discovered this repository and was excited to start using it. However, today I came across the [v2.0.0 release](https://github.com/stackbuilders/nixpkgs-terraform/releases/tag/v2.0.0), and it left me a bit puzzled.

At my workplace, we use a mix of different Terraform versions, ranging from 0.12.X to 1.5.X. Initially, I thought this repository would provide me access to these Terraform versions. However, it exports only the currently supported versions, which are 1.6 and 1.7, at the moment. In my opinion, this limitation significantly restricts the usefulness of this repository, making it almost identical to the upstream `nixpkgs`.

Contrastingly, other repositories, such as [cachix/nixpkgs-python](https://github.com/cachix/nixpkgs-python) or [oxalica/rust-overlay](https://github.com/oxalica/rust-overlay), offer packages for versions that are no longer supported. For instance, Python 2.7, which reached the end of its support in 2020, is still [available in nixpkgs-python](https://github.com/cachix/nixpkgs-python/blob/d530242aee46505e2a950b93760bbe7c9f9b2442/versions.json#L527-L542). Similarly, Rust 1.30.0 is still [provided in rust-overlay](https://github.com/oxalica/rust-overlay/blob/883b84c426107a8ec020e7124f263d7c35a5bb9f/manifests/stable/1.30.0.nix).

Would you consider exporting unsupported Terraform versions for compatibility purposes?

**Comment by sestrella** [comment]
@pedorich-n thank you for the feedback. I believe the main reason why we decided to drop support for older versions is that it makes it difficult to perform updates over the `nixpkgs` input, as we are trying to build all versions against the same `pkgs.mkTerraform` to avoid managing multiple `nixpkgs` in the code. But your points are valid; I believe this is a decision we could revisit as this is a project that still in its early stages. I'm planning to have a discussion with @oscar-izval who is the co-creator of this project and come back as soon as possible.

**Comment by sestrella** [comment]
@pedorich-n after thoughtful consideration, @oscar-izval and I agree to preserve support for EOL versions and extend support for all 1.x, including patch versions. For the time being, we believe 1.0 to be an acceptable lower bound, as we seek to balance maintenance efforts against supported versions. The door to adding support for 0.x versions is not closed, but, as a relative new project, we believe it is preferable to draw a line around 1.x for now and get more feedback from the community before expanding the support.

Next steps include gradually adding support for all 1.x versions. Óscar already submitted a [PR](https://github.com/stackbuilders/nixpkgs-terraform/pull/33) to add support for 1.4, and we plan to do the same for the remaining versions.

**Comment by pedorich-n** [comment]
I'm glad to hear that! 
I really think that the more versions you support, the more people will be able to use this repository.

Thanks!

**Comment by sestrella** [comment]
@pedorich-n once again, we appreciate your feedback. The latest [release](https://github.com/stackbuilders/nixpkgs-terraform/releases) adds support from Terraform 1.0 to 1.7 including all patch versions for each cycle. I'm closing this issue for now.
