### ISSUE TITLE
Are recent builds updating the binary cache?

### ISSUE THREAD

**Issue by Hamled** [stackbuilders/nixpkgs-terraform#53]
It's unclear to me whether recent runs of the Build workflow result in terraform packages built by this flake being pushed to Cachix.

Using the [latest commit in main](https://github.com/stackbuilders/nixpkgs-terraform/commit/da278f71a9e2fbc9080ddedf8d7332ba9504dbf8) to build a dev shell with `terraform-1.6.6` on `x86_64-linux` the debug log for `nix build` has:
```
checking substituter 'https://nixpkgs-terraform.cachix.org' for path '/nix/store/vfl3kpg1c1mygkyxjnc5zqpdh0qj11sm-terraform-1.6.6'
```
and ultimately no substitution was possible.

I have also built the same dev shell from [this commit](https://github.com/stackbuilders/nixpkgs-terraform/commit/733e2527610ee44fe01e7fd411705cc0600750bf), at which point the store path is `/nix/store/2v58ng2mmqvdk68s7hyk7zvr2mx5rhyi-terraform-1.6.6` which is substituted from the nixpkgs-terraform Cachix substituter.

I'm not sure if it's related or not, but [the build job log](https://github.com/stackbuilders/nixpkgs-terraform/actions/runs/7762185248/job/21172145705#step:5:33) for that commit being pushed to `main` mentions that store path (among others for different terraform versions). Job logs starting with [this one](https://github.com/stackbuilders/nixpkgs-terraform/actions/runs/7999024738/job/21846146539#step:5:13) from last week no longer mention any store paths for terraform packages.

**Comment by sestrella** [comment]
@Hamled the latest PR merge to `main` should take care of this; please let us know if you find any issues associated with the binary cache.
