### ISSUE TITLE
terraform 1.8.0 ?

### ISSUE THREAD

**Issue by sentientmonkey** [stackbuilders/nixpkgs-terraform#67]
I see that terraform 1.8.0 just released

https://github.com/hashicorp/terraform/releases/tag/v1.8.0

Is there an ETA on when this will be available for nixkpgs-terraform?

**Comment by oscar-izval** [comment]
Hey @sentientmonkey!

We have a CI job running weekly to keep the list of supported versions updated. It should run this Sunday and be available immediately after. 
That being said, I wouldn't be against running that more frequently, would that be useful to you?

@sestrella thoughts?

**Comment by sentientmonkey** [comment]
More often would be great! This helps when folks have terraform cloud set to latest. Having to wait for the nixpkgs unstable means we don't have a local install option for a bit.

**Comment by sestrella** [comment]
@oscar-izval seems like a great idea; perhaps running it twice a week would be a good move.

**Comment by oscar-izval** [comment]
I was thinking we could even do it daily, especially considering that 1.8 was released yesterday and we are already late. Besides, CI costs are negligible at this point.

**Comment by sestrella** [comment]
@oscar-izval sounds good. Would you mind submitting a PR to update the schedule of the job?

**Comment by sestrella** [comment]
@sentientmonkey Terraform 1.8.0 was included in the latest release:

https://github.com/stackbuilders/nixpkgs-terraform/releases/tag/v3.2.0

**Comment by sentientmonkey** [comment]
Thanks so much! ❤️
